export type UseCase = "date" | "friends" | "solo" | "family";

export type TimeWindow = "tonight" | "halfday" | "fullday";
export type Budget = "low" | "medium" | "high";
export type Mood = "cozy" | "active" | "romantic" | "fun" | "chill";
export type Place = "indoors" | "outdoors" | "either";

export type Idea = {
  id: string;
  useCase: UseCase;
  title: string;
  description: string;
  steps: string[];
  timeWindows: TimeWindow[];
  budgets: Budget[];
  moods: Mood[];
  place: Place;
};

export const IDEAS: Idea[] = [
  // =========================
  // DATE
  // =========================
  {
  id: "date-sunset-picnic-express",
  useCase: "date",
  title: "Sunset picnic (express version)",
  description: "A romantic moment without planning overload.",
  steps: ["Buy ready-made snacks", "Find a sunset spot", "Eat + watch sunset", "Short walk after"],
  timeWindows: ["tonight"],
  budgets: ["low", "medium"],
  moods: ["romantic", "cozy"],
  place: "outdoors",
},
{
  id: "date-pottery-or-paint-night",
  useCase: "date",
  title: "Paint or pottery night",
  description: "Creative, relaxed, and great conversation.",
  steps: ["Choose a simple class or DIY kit", "Create something small", "Laugh at results", "Take it home"],
  timeWindows: ["tonight", "halfday"],
  budgets: ["medium"],
  moods: ["cozy", "fun"],
  place: "indoors",
},
{
  id: "date-late-night-dessert",
  useCase: "date",
  title: "Late-night dessert mission",
  description: "Skip dinner. Go straight for something sweet.",
  steps: ["Find a dessert place open late", "Share one thing", "Sit and talk", "Walk it off"],
  timeWindows: ["tonight"],
  budgets: ["low", "medium"],
  moods: ["romantic", "fun"],
  place: "either",
},
  {
    id: "date-sunset-walk-hot-drink",
    useCase: "date",
    title: "Sunset walk + a warm drink",
    description: "Keep it simple: a scenic walk and something warm to end the night.",
    steps: ["Pick a park/viewpoint", "Walk 30–60 minutes", "Grab tea/coffee/hot chocolate", "Optional: share one dessert"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["romantic", "cozy", "chill"],
    place: "outdoors",
  },
  {
    id: "date-mini-food-tour",
    useCase: "date",
    title: "Mini food tour (3 stops)",
    description: "One appetizer, one main, one dessert — different places, one night.",
    steps: ["Choose 3 spots close by", "Share plates", "Take one photo per stop", "End with a short night walk"],
    timeWindows: ["tonight"],
    budgets: ["medium", "high"],
    moods: ["fun", "romantic"],
    place: "either",
  },
  {
    id: "date-museum-to-dinner",
    useCase: "date",
    title: "Museum/gallery + casual dinner",
    description: "Built-in conversation fuel, low pressure, works in any city.",
    steps: ["Pick a small exhibit", "Choose 3 favorite pieces each", "Grab dinner nearby", "Do a 10-minute recap: best moment"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["medium", "high"],
    moods: ["cozy", "romantic", "chill"],
    place: "indoors",
  },
  {
    id: "date-game-night-best-of-3",
    useCase: "date",
    title: "Game night (best of 3)",
    description: "A playful night in. One fast game + one longer one.",
    steps: ["Pick 2 games", "Agree on a fun reward", "Play best-of-3", "Put on a chill playlist"],
    timeWindows: ["tonight"],
    budgets: ["low", "medium"],
    moods: ["fun", "cozy", "chill"],
    place: "indoors",
  },
  {
    id: "date-picnic-lite",
    useCase: "date",
    title: "Simple picnic (no overthinking)",
    description: "Two snacks, one drink, one blanket. That’s it.",
    steps: ["Buy 2 snacks", "Bring a blanket", "Pick a calm spot", "Ask 5 good questions"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["romantic", "cozy", "chill"],
    place: "outdoors",
  },
  {
    id: "date-cook-together-one-pan",
    useCase: "date",
    title: "Cook together (one-pan meal)",
    description: "Low effort, high teamwork. Keep it simple and fun.",
    steps: ["Pick one-pan pasta or tacos", "Split roles (prep vs. cook)", "Eat with no phones", "End with a short walk or dessert"],
    timeWindows: ["tonight"],
    budgets: ["low", "medium"],
    moods: ["cozy", "romantic"],
    place: "indoors",
  },
  {
    id: "date-coffee-dessert-crawl",
    useCase: "date",
    title: "Coffee + dessert crawl",
    description: "Two cafés, one shared dessert each. Easy, cute, and chatty.",
    steps: ["Pick 2 cafés", "Share one dessert at each", "Rate them 1–10", "Declare a winner"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["medium"],
    moods: ["fun", "cozy", "romantic"],
    place: "either",
  },
  {
    id: "date-day-trip-nearby-town",
    useCase: "date",
    title: "Day trip to a nearby town",
    description: "A mini adventure without planning stress.",
    steps: ["Pick a town within 60–90 min", "Choose 1 walk + 1 café", "Do a small photo challenge", "Head home before it gets tiring"],
    timeWindows: ["halfday", "fullday"],
    budgets: ["medium"],
    moods: ["romantic", "chill", "fun"],
    place: "either",
  },

  // =========================
  // FRIENDS
  // =========================
  {
  id: "friends-random-country-dinner",
  useCase: "friends",
  title: "Random country dinner night",
  description: "Spin a country and cook something from there.",
  steps: ["Randomize a country", "Google 1 simple dish", "Cook together", "Rate the result"],
  timeWindows: ["tonight"],
  budgets: ["low", "medium"],
  moods: ["fun"],
  place: "indoors",
},
{
  id: "friends-escape-room-home",
  useCase: "friends",
  title: "Home escape room",
  description: "Puzzle-solving without leaving the house.",
  steps: ["Print or load an online escape game", "Set a timer", "Split into teams", "Celebrate success/failure"],
  timeWindows: ["tonight"],
  budgets: ["low"],
  moods: ["fun"],
  place: "indoors",
},
{
  id: "friends-bar-crawl-lite",
  useCase: "friends",
  title: "Bar crawl (lite version)",
  description: "2–3 places max. Quality over chaos.",
  steps: ["Pick 2–3 nearby bars", "One drink per place", "End early", "Late-night food optional"],
  timeWindows: ["tonight"],
  budgets: ["medium"],
  moods: ["fun"],
  place: "indoors",
},
  {
    id: "friends-taco-ranking-night",
    useCase: "friends",
    title: "Taco ranking night",
    description: "Try 3 places (or 3 fillings). Rate each one. Crown a champion.",
    steps: ["Pick 3 taco options", "Share and rate each", "Make a quick top-3 list", "Winner chooses next hangout"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["fun", "chill"],
    place: "either",
  },
  {
    id: "friends-boardgames-bracket",
    useCase: "friends",
    title: "Board game bracket",
    description: "A mini tournament: fast rounds, lots of laughs.",
    steps: ["Pick 3 short games", "Make a simple bracket", "Play 20-min rounds", "Loser brings snacks next time"],
    timeWindows: ["tonight"],
    budgets: ["low"],
    moods: ["fun", "cozy"],
    place: "indoors",
  },
  {
    id: "friends-walk-and-talk-loop",
    useCase: "friends",
    title: "Walk-and-talk loop",
    description: "A no-cost hangout that always works — add a coffee stop.",
    steps: ["Choose a 45–90 min loop", "Grab coffee to-go", "Do a 'high/low of the week' round", "Finish somewhere cozy"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["chill", "cozy"],
    place: "outdoors",
  },
  {
    id: "friends-karaoke-living-room",
    useCase: "friends",
    title: "Living room karaoke",
    description: "No stage needed. Just a speaker and boldness.",
    steps: ["Pick a YouTube karaoke playlist", "Do 1 warm-up song each", "Theme round (90s / guilty pleasure)", "Finale: group song"],
    timeWindows: ["tonight"],
    budgets: ["low"],
    moods: ["fun"],
    place: "indoors",
  },
  {
    id: "friends-activity-pub-quiz",
    useCase: "friends",
    title: "Pub quiz night",
    description: "Easy social energy. Everyone gets invested fast.",
    steps: ["Find a quiz spot", "Arrive 15 min early", "Assign roles (music/sports/random)", "Celebrate any win (even small)"],
    timeWindows: ["tonight"],
    budgets: ["medium"],
    moods: ["fun", "chill"],
    place: "indoors",
  },
  {
    id: "friends-pickup-sport",
    useCase: "friends",
    title: "Pickup sport (low commitment)",
    description: "Basketball, padel, football, whatever’s easy to book.",
    steps: ["Pick something bookable", "Keep it 60–90 min", "No teams? do king-of-the-court", "Cooldown snack after"],
    timeWindows: ["halfday"],
    budgets: ["medium"],
    moods: ["active", "fun"],
    place: "either",
  },
  {
    id: "friends-night-market-mission",
    useCase: "friends",
    title: "Night market / street food mission",
    description: "Walk, snack, and vote for the best bite.",
    steps: ["Go to a food spot/market area", "Each person picks one must-try", "Share bites", "Rank top 3 together"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["medium"],
    moods: ["fun"],
    place: "either",
  },

  // =========================
  // SOLO
  // =========================
  {
  id: "solo-evening-reset-walk",
  useCase: "solo",
  title: "Evening reset walk",
  description: "Clear your head and reset the day.",
  steps: ["Leave phone on silent", "Walk 30–45 minutes", "Breathe deeply", "Stretch at home"],
  timeWindows: ["tonight"],
  budgets: ["low"],
  moods: ["chill"],
  place: "outdoors",
},
{
  id: "solo-learn-something-1-hour",
  useCase: "solo",
  title: "Learn one thing in 1 hour",
  description: "Progress without pressure.",
  steps: ["Pick one topic", "Watch 1–2 videos", "Write 3 notes", "Stop after 60 minutes"],
  timeWindows: ["tonight", "halfday"],
  budgets: ["low"],
  moods: ["cozy", "chill"],
  place: "indoors",
},
{
  id: "solo-sunday-planning-lite",
  useCase: "solo",
  title: "Light life admin session",
  description: "A small effort that pays off later.",
  steps: ["Clean inbox for 15 min", "Plan next week lightly", "Set 1 goal", "Reward yourself"],
  timeWindows: ["tonight"],
  budgets: ["low"],
  moods: ["chill"],
  place: "indoors",
},
  {
    id: "solo-cafe-reset-hour",
    useCase: "solo",
    title: "Café reset hour",
    description: "A mental reset: one drink, one small plan for tomorrow.",
    steps: ["Pick a calm café", "No phone for 10 minutes", "Write 3 priorities for tomorrow", "Leave with a simple next step"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["cozy", "chill"],
    place: "indoors",
  },
  {
    id: "solo-photo-walk-10-shots",
    useCase: "solo",
    title: "Photo walk (10-shot challenge)",
    description: "Give your brain a fun mission and explore your area.",
    steps: ["Choose a neighborhood", "Take 10 photos with a theme", "Pick your best 2", "Share or save them"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low"],
    moods: ["chill", "fun"],
    place: "outdoors",
  },
  {
    id: "solo-gym-plus-sauna",
    useCase: "solo",
    title: "Workout + sauna (or long stretch)",
    description: "Move your body, then recover properly.",
    steps: ["Do a simple 30–45 min session", "10 min cooldown", "Sauna or long stretch", "Hydrate and eat something decent"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["active", "chill"],
    place: "indoors",
  },
  {
    id: "solo-museum-slow",
    useCase: "solo",
    title: "Museum, but slow",
    description: "Pick one section and actually take your time.",
    steps: ["Choose one exhibit", "Read the labels", "Pick one favorite piece", "Write 3 thoughts after"],
    timeWindows: ["halfday"],
    budgets: ["medium"],
    moods: ["cozy", "chill"],
    place: "indoors",
  },
  {
    id: "solo-day-trip-nature-loop",
    useCase: "solo",
    title: "Nature loop day trip",
    description: "A low-stress escape: walk, breathe, return refreshed.",
    steps: ["Pick a trail/park", "Bring water + snack", "Walk 60–120 min", "Leave before you’re exhausted"],
    timeWindows: ["halfday", "fullday"],
    budgets: ["low", "medium"],
    moods: ["chill", "active"],
    place: "outdoors",
  },

  // =========================
  // FAMILY
  // =========================
  {
  id: "family-build-fort-night",
  useCase: "family",
  title: "Build-a-fort night",
  description: "Blankets, pillows, imagination.",
  steps: ["Build a fort together", "Bring snacks inside", "Read or watch something", "Sleepover optional"],
  timeWindows: ["tonight"],
  budgets: ["low"],
  moods: ["fun", "cozy"],
  place: "indoors",
},
{
  id: "family-bike-ride-ice-cream",
  useCase: "family",
  title: "Bike ride + ice cream",
  description: "Movement plus a clear reward.",
  steps: ["Plan a short bike route", "Ride at kids’ pace", "Ice cream stop", "Head home happy"],
  timeWindows: ["halfday"],
  budgets: ["low", "medium"],
  moods: ["active", "fun"],
  place: "outdoors",
},
{
  id: "family-cooking-challenge",
  useCase: "family",
  title: "Family cooking challenge",
  description: "Teams, creativity, and fun mess.",
  steps: ["Split into teams", "Choose ingredients", "Cook simple dishes", "Taste and vote"],
  timeWindows: ["halfday"],
  budgets: ["low", "medium"],
  moods: ["fun"],
  place: "indoors",
},
  {
    id: "family-pancake-then-park",
    useCase: "family",
    title: "Pancakes + park mission",
    description: "Simple and reliable: food first, then burn energy.",
    steps: ["Make pancakes together", "Let kids pick toppings", "Go to a park/playground", "End with a small treat"],
    timeWindows: ["halfday"],
    budgets: ["low", "medium"],
    moods: ["fun", "cozy"],
    place: "either",
  },
  {
    id: "family-movie-night-pick-roles",
    useCase: "family",
    title: "Movie night with roles",
    description: "Make it interactive: one chooses movie, one snacks, one blankets.",
    steps: ["Assign roles (movie/snacks/cozy)", "Pick a family-friendly film", "Phones away", "Quick 'best part' recap after"],
    timeWindows: ["tonight"],
    budgets: ["low"],
    moods: ["cozy", "chill"],
    place: "indoors",
  },
  {
    id: "family-scavenger-hunt-indoors",
    useCase: "family",
    title: "Indoor scavenger hunt",
    description: "Turns boredom into a game in 5 minutes.",
    steps: ["Write 10 simple items", "Set a 10-minute timer", "Team up or solo", "Winner picks the next activity"],
    timeWindows: ["tonight"],
    budgets: ["low"],
    moods: ["fun"],
    place: "indoors",
  },
  {
    id: "family-zoo-or-aquarium",
    useCase: "family",
    title: "Zoo / aquarium mini-trip",
    description: "A classic half-day that feels like a real outing.",
    steps: ["Go early if possible", "Pick 3 must-see animals", "Snack break halfway", "Let kids take photos"],
    timeWindows: ["halfday", "fullday"],
    budgets: ["medium", "high"],
    moods: ["fun", "active"],
    place: "either",
  },
  {
    id: "family-library-plus-hot-chocolate",
    useCase: "family",
    title: "Library + hot chocolate",
    description: "Cheap, calm, and surprisingly satisfying.",
    steps: ["Let everyone pick 1 book", "Read together 15–20 min", "Grab hot chocolate", "Talk about favorite part"],
    timeWindows: ["tonight", "halfday"],
    budgets: ["low", "medium"],
    moods: ["cozy", "chill"],
    place: "indoors",
  },
];
