import type { Idea, UseCase, TimeWindow, Budget, Mood, Place } from "./types";


type Template = {
  id: string;
  title: string;
  baseDescription: string;
  steps: string[];
  useCases: UseCase[];
  moods: Mood[];
  budgets: Budget[];
  place: Place;
  minTime: TimeWindow;
};

const TEMPLATES: Template[] = [
  {
    id: "coffee-walk",
    title: "Coffee walk",
    baseDescription: "A simple walk with a coffee in hand.",
    steps: ["Grab coffee to-go", "Walk a calm route", "Talk or observe", "Optional second stop"],
    useCases: ["date", "friends", "solo"],
    moods: ["cozy", "chill"],
    budgets: ["low", "medium"],
    place: "outdoors",
    minTime: "tonight",
  },
  {
    id: "food-crawl",
    title: "Mini food crawl",
    baseDescription: "Multiple small stops instead of one big plan.",
    steps: ["Pick 2–3 nearby places", "Share something at each", "Rate them", "Pick a winner"],
    useCases: ["date", "friends"],
    moods: ["fun", "romantic"],
    budgets: ["medium", "high"],
    place: "either",
    minTime: "tonight",
  },
  {
    id: "nature-loop",
    title: "Nature loop escape",
    baseDescription: "A reset in nature with zero pressure.",
    steps: ["Choose a loop trail", "Walk at easy pace", "Take a break halfway", "Head back before tired"],
    useCases: ["solo", "date", "family"],
    moods: ["chill", "active"],
    budgets: ["low", "medium"],
    place: "outdoors",
    minTime: "halfday",
  },
  {
    id: "daytrip-town",
    title: "Nearby town day trip",
    baseDescription: "A small adventure that feels bigger than it is.",
    steps: ["Pick a town within 1–2h", "Walk the center", "Eat somewhere local", "Return before evening"],
    useCases: ["date", "friends", "family", "solo"],
    moods: ["fun", "chill", "romantic"],
    budgets: ["medium"],
    place: "either",
    minTime: "fullday",
  },
    {
    id: "street-food-mission",
    title: "Street food mission",
    baseDescription: "Try something new without overplanning.",
    steps: ["Pick a food area", "Choose 1 must-try item", "Share + rate it", "Optional: second stop"],
    useCases: ["date", "friends", "family"],
    moods: ["fun", "chill", "cozy"],
    budgets: ["low", "medium"],
    place: "either",
    minTime: "tonight",
  },
  {
    id: "movie-plus-walk",
    title: "Movie + short walk",
    baseDescription: "Easy evening plan with a clean finish.",
    steps: ["Pick a movie", "Keep snacks simple", "Walk 15–30 minutes after", "Quick recap: best scene"],
    useCases: ["date", "friends", "family", "solo"],
    moods: ["cozy", "chill", "romantic"],
    budgets: ["low", "medium"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "museum-one-room",
    title: "One-room museum / gallery",
    baseDescription: "A small culture hit that’s surprisingly satisfying.",
    steps: ["Pick a small exhibit", "Each chooses 2 favorites", "Discuss why", "Grab a drink after"],
    useCases: ["date", "friends", "solo"],
    moods: ["cozy", "chill", "romantic"],
    budgets: ["medium"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "bookstore-and-cafe",
    title: "Bookstore + café",
    baseDescription: "Browse, pick something, and sit down for a calm break.",
    steps: ["Browse 15 minutes", "Pick 1 book/item each", "Café sit-down", "Share one interesting find"],
    useCases: ["date", "friends", "solo", "family"],
    moods: ["cozy", "chill", "romantic"],
    budgets: ["low", "medium"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "sunset-viewpoint",
    title: "Sunset viewpoint",
    baseDescription: "A simple outdoor moment with big payoff.",
    steps: ["Pick a viewpoint", "Bring a drink", "Watch sunset", "Walk back slowly"],
    useCases: ["date", "friends", "solo"],
    moods: ["romantic", "chill", "cozy"],
    budgets: ["low", "medium"],
    place: "outdoors",
    minTime: "tonight",
  },
  {
    id: "cafe-rating-crawl",
    title: "Café rating crawl",
    baseDescription: "Two cafés, one rating sheet. Keep it light and fun.",
    steps: ["Pick 2 cafés close by", "Order one thing each", "Rate 1–10", "Declare a winner"],
    useCases: ["date", "friends"],
    moods: ["fun", "cozy", "romantic"],
    budgets: ["medium"],
    place: "either",
    minTime: "tonight",
  },
  {
    id: "home-cook-off",
    title: "Simple cook-off",
    baseDescription: "Make dinner into a mini game.",
    steps: ["Pick one dish category", "Split roles or teams", "Cook simple versions", "Taste + vote"],
    useCases: ["date", "friends", "family"],
    moods: ["fun", "cozy"],
    budgets: ["low", "medium"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "picnic-blanket",
    title: "Blanket picnic",
    baseDescription: "Two snacks, one drink, one blanket. That’s enough.",
    steps: ["Buy 2 snacks", "Bring blanket", "Pick calm spot", "Stay 30–60 minutes"],
    useCases: ["date", "friends", "family"],
    moods: ["cozy", "romantic", "chill"],
    budgets: ["low", "medium"],
    place: "outdoors",
    minTime: "halfday",
  },
  {
    id: "mini-hike",
    title: "Mini hike / long walk",
    baseDescription: "Move a bit, breathe, feel better after.",
    steps: ["Pick a trail/route", "Bring water", "Walk 60–120 minutes", "Snack break"],
    useCases: ["friends", "solo", "family", "date"],
    moods: ["active", "chill"],
    budgets: ["low", "medium"],
    place: "outdoors",
    minTime: "halfday",
  },
  {
    id: "sports-casual",
    title: "Casual sport session",
    baseDescription: "Keep it friendly and low pressure.",
    steps: ["Pick an easy sport", "Play 45–90 minutes", "Cooldown", "Food/drink after"],
    useCases: ["friends", "solo"],
    moods: ["active", "fun"],
    budgets: ["low", "medium"],
    place: "either",
    minTime: "halfday",
  },
  {
    id: "thrift-store-challenge",
    title: "Thrift store challenge",
    baseDescription: "Find something weird, useful, or surprisingly stylish.",
    steps: ["Set a small budget", "15-minute hunt", "Show-and-tell", "Optional: buy 1 item"],
    useCases: ["friends", "date"],
    moods: ["fun"],
    budgets: ["low", "medium"],
    place: "indoors",
    minTime: "halfday",
  },
  {
    id: "photo-mission-10",
    title: "10-photo mission",
    baseDescription: "Turn wandering into a mission with a theme.",
    steps: ["Pick a theme (colors/doors/food)", "Take 10 photos", "Choose best 2", "Share or save"],
    useCases: ["solo", "friends", "date", "family"],
    moods: ["fun", "chill"],
    budgets: ["low"],
    place: "outdoors",
    minTime: "halfday",
  },
  {
    id: "market-and-cook",
    title: "Market + cook something simple",
    baseDescription: "Buy ingredients together and cook one easy meal.",
    steps: ["Go to a store/market", "Pick 3 ingredients", "Cook a simple dish", "Eat with no rush"],
    useCases: ["date", "friends", "family"],
    moods: ["cozy", "fun"],
    budgets: ["low", "medium"],
    place: "indoors",
    minTime: "halfday",
  },
  {
    id: "aquarium-or-zoo",
    title: "Aquarium / zoo",
    baseDescription: "A classic outing that works for nearly anyone.",
    steps: ["Go early if possible", "Pick 3 must-see things", "Snack break", "Wrap before tired"],
    useCases: ["family", "date", "friends"],
    moods: ["fun", "active", "chill"],
    budgets: ["medium", "high"],
    place: "either",
    minTime: "halfday",
  },
  {
    id: "spa-recovery",
    title: "Recovery session (sauna / spa / long stretch)",
    baseDescription: "Get your body feeling better in under 2 hours.",
    steps: ["Move lightly first", "Sauna/spa or long stretch", "Hydrate", "Early night"],
    useCases: ["solo", "date"],
    moods: ["chill", "cozy"],
    budgets: ["medium", "high"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "free-event-hunt",
    title: "Find a free local event",
    baseDescription: "A small local event = instant story + social energy.",
    steps: ["Search ‘free events’ nearby", "Pick one that starts soon", "Go for 60–120 minutes", "Debrief after"],
    useCases: ["friends", "date", "family", "solo"],
    moods: ["fun", "chill"],
    budgets: ["low", "medium"],
    place: "either",
    minTime: "tonight",
  },
  {
    id: "bowling-or-arcade",
    title: "Bowling / arcade session",
    baseDescription: "Low-skill, high-laugh activity that fills an evening.",
    steps: ["Book or walk in", "Play 60–90 minutes", "Small prize for winner", "Snack after"],
    useCases: ["date", "friends", "family"],
    moods: ["fun", "active"],
    budgets: ["medium"],
    place: "indoors",
    minTime: "tonight",
  },
  {
    id: "scenic-drive",
    title: "Scenic drive + one stop",
    baseDescription: "A low-effort mini adventure with a view.",
    steps: ["Pick a scenic direction", "Drive 30–60 minutes", "Stop for a view/snack", "Drive back relaxed"],
    useCases: ["date", "friends", "family", "solo"],
    moods: ["chill", "romantic", "fun"],
    budgets: ["low", "medium"],
    place: "either",
    minTime: "halfday",
  },
  {
    id: "full-day-multi-stop",
    title: "Full-day multi-stop adventure",
    baseDescription: "A simple structure for a full day: walk + food + one activity.",
    steps: ["Choose a walk", "Choose a food stop", "Choose one activity", "Leave time for one spontaneous stop"],
    useCases: ["date", "friends", "family", "solo"],
    moods: ["fun", "active", "chill", "romantic"],
    budgets: ["low", "medium", "high"],
    place: "either",
    minTime: "fullday",
  },
  {
    id: "cozy-home-night",
    title: "Cozy home night",
    baseDescription: "A simple night in that still feels like a plan.",
    steps: ["Set a playlist", "Make one snack", "Do one activity (game/movie)", "No phones for 30 minutes"],
    useCases: ["date", "friends", "family", "solo"],
    moods: ["cozy", "chill", "romantic"],
    budgets: ["low"],
    place: "indoors",
    minTime: "tonight",
  },

{
  id: "luxury-day-reset",
  title: "Luxury reset day",
  baseDescription: "A premium day focused on comfort, food, and zero stress.",
  steps: ["Late start", "One premium experience", "Long lunch", "Relaxed end"],
  useCases: ["date", "solo"],
  moods: ["chill", "romantic", "cozy"],
  budgets: ["high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "multi-stop-food-day",
  title: "Multi-stop food day",
  baseDescription: "Let meals structure the entire day.",
  steps: ["Breakfast spot", "Walk", "Lunch", "Dessert stop"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "cozy", "romantic"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "guided-outdoor-experience",
  title: "Guided outdoor experience",
  baseDescription: "An activity where everything is already planned.",
  steps: ["Arrive on time", "Follow the guide", "Enjoy the activity", "Food after"],
  useCases: ["friends", "date", "solo"],
  moods: ["active", "fun"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "halfday",
},
{
  id: "slow-coastal-day",
  title: "Slow coastal day",
  baseDescription: "Sea air, calm walks, and great food.",
  steps: ["Travel to coast", "Long walk", "Seafood lunch", "Sunset stop"],
  useCases: ["date", "friends", "family"],
  moods: ["romantic", "chill", "cozy"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "city-neighborhood-hop",
  title: "Neighborhood hopping",
  baseDescription: "Explore different parts of the city without rushing.",
  steps: ["Pick 2–3 areas", "Walk between", "One café stop", "One food stop"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "chill"],
  budgets: ["low", "medium"],
  place: "either",
  minTime: "halfday",
},
{
  id: "nature-spa-combo",
  title: "Nature + spa combo",
  baseDescription: "Balance movement with recovery.",
  steps: ["Outdoor walk", "Spa/sauna", "Light meal", "Early finish"],
  useCases: ["date", "solo"],
  moods: ["chill", "cozy"],
  budgets: ["high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "full-day-road-loop",
  title: "Full-day road loop",
  baseDescription: "Drive, explore, and return without stress.",
  steps: ["Plan loop", "Stop 2–3 times", "Eat local", "Return before late"],
  useCases: ["date", "friends", "family", "solo"],
  moods: ["fun", "chill"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "luxury-culture-day",
  title: "Luxury culture day",
  baseDescription: "Art, architecture, and premium breaks.",
  steps: ["Museum/gallery", "Lunch nearby", "Second exhibit", "Coffee or drink"],
  useCases: ["date", "solo"],
  moods: ["cozy", "romantic"],
  budgets: ["high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "outdoor-activity-plus-food",
  title: "Outdoor activity + food",
  baseDescription: "Move first, eat well after.",
  steps: ["Active session", "Cooldown", "Proper meal", "Relax"],
  useCases: ["friends", "date", "solo"],
  moods: ["active", "fun"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "halfday",
},
{
  id: "family-adventure-day",
  title: "Family adventure day",
  baseDescription: "A full day that works for all ages.",
  steps: ["Start early", "Main attraction", "Breaks", "Leave before tired"],
  useCases: ["family"],
  moods: ["fun", "active"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "romantic-slow-day",
  title: "Romantic slow day",
  baseDescription: "A full day without rushing or pressure.",
  steps: ["Late breakfast", "Walk together", "Long lunch", "Early evening finish"],
  useCases: ["date"],
  moods: ["romantic", "cozy", "chill"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "urban-explorer-day",
  title: "Urban explorer day",
  baseDescription: "Architecture, streets, and hidden spots.",
  steps: ["Choose route", "Walk + explore", "Lunch stop", "Final viewpoint"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "chill"],
  budgets: ["low", "medium"],
  place: "outdoors",
  minTime: "halfday",
},
{
  id: "premium-shopping-break",
  title: "Premium shopping + break",
  baseDescription: "Browse without pressure and enjoy the setting.",
  steps: ["Pick area", "Browse freely", "Coffee/lunch", "One intentional buy"],
  useCases: ["date", "solo", "friends"],
  moods: ["cozy", "chill"],
  budgets: ["high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "seasonal-highlight-day",
  title: "Seasonal highlight day",
  baseDescription: "Focus on what’s best right now.",
  steps: ["Find seasonal activity", "Arrive early", "Explore", "Food break"],
  useCases: ["date", "friends", "family", "solo"],
  moods: ["fun", "chill"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "halfday",
},
{
  id: "island-hopping-lite",
  title: "Island hopping (lite)",
  baseDescription: "Water views and slow movement.",
  steps: ["Boat/ferry", "Walk island", "Eat", "Return relaxed"],
  useCases: ["date", "friends"],
  moods: ["romantic", "chill"],
  budgets: ["high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "active-nature-day",
  title: "Active nature day",
  baseDescription: "A full day built around movement.",
  steps: ["Main hike/activity", "Breaks", "Good food", "Stretch"],
  useCases: ["friends", "solo", "date"],
  moods: ["active", "fun"],
  budgets: ["medium"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "slow-home-luxury",
  title: "Slow luxury at home",
  baseDescription: "Turn staying in into a premium experience.",
  steps: ["Set mood", "Cook or order premium food", "No phones", "Early night"],
  useCases: ["date", "solo"],
  moods: ["cozy", "romantic", "chill"],
  budgets: ["medium", "high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "friends-experience-day",
  title: "Friends experience day",
  baseDescription: "One booked experience and time around it.",
  steps: ["Book activity", "Participate", "Food after", "Relaxed finish"],
  useCases: ["friends"],
  moods: ["fun", "active"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "halfday",
},
{
  id: "long-walk-and-talk",
  title: "Long walk & talk day",
  baseDescription: "Simple structure, deep conversations.",
  steps: ["Choose long route", "Walk slowly", "Food break", "Finish calm"],
  useCases: ["date", "friends", "solo"],
  moods: ["chill", "cozy", "romantic"],
  budgets: ["low", "medium"],
  place: "outdoors",
  minTime: "halfday",
},
{
  id: "high-end-dining-day",
  title: "High-end dining focus",
  baseDescription: "Make the meal the main event.",
  steps: ["Book restaurant", "Arrive early", "Enjoy slowly", "Walk after"],
  useCases: ["date"],
  moods: ["romantic", "cozy"],
  budgets: ["high"],
  place: "indoors",
  minTime: "halfday",
},

{
  id: "city-day-explorer",
  title: "City explorer day",
  baseDescription: "Experience the city without rushing from place to place.",
  steps: ["Start in one neighborhood", "Walk + explore", "Eat well", "Add one spontaneous stop"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "chill", "romantic"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "halfday",
},
{
  id: "spa-and-lunch",
  title: "Spa + long lunch",
  baseDescription: "A slow luxury day focused on recovery and comfort.",
  steps: ["Book spa session", "Relax properly", "Long lunch nearby", "Leave early evening"],
  useCases: ["date", "solo"],
  moods: ["chill", "cozy", "romantic"],
  budgets: ["high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "coastal-daytrip",
  title: "Coastal day trip",
  baseDescription: "Sea air, good food, and a full reset.",
  steps: ["Drive/train to coast", "Walk along water", "Seafood lunch", "Viewpoint stop"],
  useCases: ["date", "friends", "family"],
  moods: ["chill", "romantic", "fun"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "mountain-or-nature-resort",
  title: "Nature resort escape",
  baseDescription: "A day surrounded by nature with comfort included.",
  steps: ["Travel to resort", "Nature walk", "Good meal", "Relaxed return"],
  useCases: ["date", "solo", "family"],
  moods: ["chill", "cozy", "romantic"],
  budgets: ["high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "theme-park-day",
  title: "Theme park day",
  baseDescription: "A full day built around rides, food, and energy.",
  steps: ["Arrive early", "Ride highlights", "Food break", "End before exhaustion"],
  useCases: ["friends", "family", "date"],
  moods: ["fun", "active"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "winery-or-brewery-tour",
  title: "Winery / brewery tour",
  baseDescription: "Taste, learn, and enjoy without stress.",
  steps: ["Book tasting", "Learn the process", "Enjoy lunch", "Bring something home"],
  useCases: ["date", "friends"],
  moods: ["romantic", "fun", "chill"],
  budgets: ["medium", "high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "food-capital-day",
  title: "Food-focused day",
  baseDescription: "Let meals be the structure of the entire day.",
  steps: ["Breakfast spot", "Walk between stops", "Long lunch", "Dessert finale"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "cozy", "romantic"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "guided-experience",
  title: "Guided experience or tour",
  baseDescription: "Let someone else handle the structure.",
  steps: ["Book guided activity", "Participate fully", "Ask questions", "Debrief after"],
  useCases: ["date", "friends", "solo"],
  moods: ["fun", "chill"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "halfday",
},
{
  id: "roadtrip-loop",
  title: "Road trip loop",
  baseDescription: "Drive, stop, explore, repeat.",
  steps: ["Plan a loop route", "Stop at 2–3 places", "Eat somewhere local", "Return before late"],
  useCases: ["date", "friends", "family", "solo"],
  moods: ["fun", "chill", "romantic"],
  budgets: ["medium", "high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "luxury-shopping-day",
  title: "Luxury shopping + break",
  baseDescription: "Browse without pressure and enjoy the surroundings.",
  steps: ["Pick a shopping area", "Browse freely", "Coffee/lunch break", "One intentional purchase"],
  useCases: ["date", "solo", "friends"],
  moods: ["cozy", "chill"],
  budgets: ["high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "outdoor-adventure-day",
  title: "Outdoor adventure day",
  baseDescription: "An active day with planned highlights.",
  steps: ["Choose main activity", "Gear up", "Take breaks", "Good meal after"],
  useCases: ["friends", "solo", "date"],
  moods: ["active", "fun"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "fullday",
},
{
  id: "cultural-deep-dive",
  title: "Cultural deep dive",
  baseDescription: "Museums, architecture, and local culture.",
  steps: ["Pick 1–2 cultural spots", "Take time at each", "Discuss highlights", "End with café"],
  useCases: ["date", "solo", "friends"],
  moods: ["cozy", "chill"],
  budgets: ["medium", "high"],
  place: "indoors",
  minTime: "halfday",
},
{
  id: "slow-luxury-day",
  title: "Slow luxury day",
  baseDescription: "Comfort, time, and no rushing.",
  steps: ["Late start", "One premium experience", "Long meal", "Early finish"],
  useCases: ["date", "solo"],
  moods: ["romantic", "chill", "cozy"],
  budgets: ["high"],
  place: "either",
  minTime: "fullday",
},
{
  id: "seasonal-event-day",
  title: "Seasonal event day",
  baseDescription: "Markets, festivals, or seasonal highlights.",
  steps: ["Find seasonal event", "Arrive early", "Explore fully", "Food + rest"],
  useCases: ["friends", "family", "date"],
  moods: ["fun", "chill"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "halfday",
},
{
  id: "island-or-lake-day",
  title: "Island or lake escape",
  baseDescription: "Water, views, and a slower pace.",
  steps: ["Travel to water", "Walk/swim", "Eat nearby", "Sunset stop"],
  useCases: ["date", "friends", "family"],
  moods: ["romantic", "chill", "fun"],
  budgets: ["medium", "high"],
  place: "outdoors",
  minTime: "fullday",
},
];

const TIME_ORDER: TimeWindow[] = ["tonight", "halfday", "fullday"];

function allowedTimes(min: TimeWindow): TimeWindow[] {
  const idx = TIME_ORDER.indexOf(min);
  return TIME_ORDER.slice(idx);
}

const ALL_MOODS: Mood[] = ["cozy", "active", "romantic", "fun", "chill"];
const ALL_BUDGETS: Budget[] = ["low", "medium", "high"];

function widenBudgets(b: Budget[]): Budget[] {
  // If template is narrow, widen it to avoid dead ends
  if (b.includes("low") && b.length === 1) return ["low", "medium"];
  if (b.includes("high") && b.length === 1) return ["medium", "high"];
  return b;
}

function widenMoods(m: Mood[]): Mood[] {
  // If only one mood, allow adjacent moods too (keeps meaning but increases coverage)
  if (m.length >= 2) return m;
  const only = m[0];
  if (only === "active") return ["active", "fun", "chill"];
  if (only === "romantic") return ["romantic", "cozy", "chill"];
  if (only === "fun") return ["fun", "active", "chill"];
  if (only === "cozy") return ["cozy", "chill", "romantic"];
  return ["chill", "cozy", "fun"];
}


const TWISTS = [
  "Rate each stop 1–10",
  "Do it phone-free for 30 minutes",
  "Take 3 photos with a theme",
  "Each person picks one surprise element",
];

const ENDINGS_TONIGHT = [
  "End with a short calm walk",
  "Finish with one shared dessert",
  "Do a quick recap: best moment",
];

const ENDINGS_DAY = [
  "Add one spontaneous stop",
  "Pick a scenic viewpoint as a finale",
  "End with a relaxed café / early dinner",
];

export function generateTemplateIdeas(): Idea[] {
  const ideas: Idea[] = [];

  for (const t of TEMPLATES) {
    for (const useCase of t.useCases) {
      const times = allowedTimes(t.minTime);

      // 3 variants per template => big pool without manual writing
      const variants = [
        {
          suffix: "base",
          title: t.title,
          desc: t.baseDescription,
          extraSteps: [] as string[],
        },
        {
          suffix: "twist",
          title: `${t.title} (with a twist)`,
          desc: `${t.baseDescription} Add a small twist to make it feel new.`,
          extraSteps: [TWISTS[Math.floor(Math.random() * TWISTS.length)]],
        },
        {
          suffix: "ending",
          title: `${t.title} + a great finish`,
          desc: `${t.baseDescription} Make the ending intentional.`,
          extraSteps: [], // we add ending conditionally below
        },
      ];

      for (const v of variants) {
        ideas.push({
          id: `tpl-${t.id}-${useCase}-${v.suffix}`,
          useCase,
          title: v.title,
          description: v.desc,
          steps: [
            ...t.steps,
            ...v.extraSteps,
            // a “tonight ending” and a “day ending” are both valid;
            // we keep them as optional steps that still read well.
            ...(times.includes("fullday") ? [ENDINGS_DAY[Math.floor(Math.random() * ENDINGS_DAY.length)]] : []),
            ...(times.includes("tonight") ? [ENDINGS_TONIGHT[Math.floor(Math.random() * ENDINGS_TONIGHT.length)]] : []),
          ],
          timeWindows: times,        // ✅ BRED: matches tonight/halfday/fullday as allowed
        budgets: widenBudgets(t.budgets),
        moods: widenMoods(t.moods),
          place: t.place,
        });
      }
    }
  }

  return ideas;
}

